create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title text NOT NULL,
  url text,
  description text,
  rating float
);

insert into bookmarks (title, description, rating)
values
    ('Thinkful', 'Think outside the classroom', 5),
    ('Google', 'Where we find everything else', 4),
    ('MDN', 'The only place to find web documentation', 5),
    ('YouTube', 'Enjoy the videos and music you love', 5),
    ('NPM', 'Build amazing things', 4),
    ('GitHub', 'The secure place where over 50 million developers discover, share, and build better software', 5),
    ('W3Schools', 'Well organized and easy to understand Web building tutorials with lots of examples', 4),
    ('LinkedIn', 'An American business and employment-oriented online service', 4),
    ('PostgreSQL', 'A powerful, open source object-relational database system', 5),
    ('Heroku', 'A  platform as a service (PaaS) that enables developers to build, run, and operate', 5)